<script setup lang="ts">
import CBlock from "../CBlock.vue";
import ButtonComponent from "../ButtonComponent.vue";
import { useRouter } from "vue-router";
import { usePuzzleStore } from "../../stores/puzzles";

const store = usePuzzleStore();
const router = useRouter();
const nextChallenge = () => {
  router.push("/blockchain");
};
</script>
<template>
  <div class="flex w-full flex-col text-center items-center bg gap-5 mb-20">
    <h1
      class="text-4xl text-center items-center mb-4 mt-6"
      style="font-family: 'Times New Roman', serif"
    >
      What is a Block?
    </h1>
    <p
      class="text-md flex flex-col justify-center text-justify max-w-2xl bg-gray-200 p-20 tracking-widest"
    >
      <b>Background:</b>
      In a blockchain, a block serves as a container for transactions and
      possesses several key components. It includes a timestamp marking its
      creation, crucial for establishing the blockchain's chronological order
      and safeguarding against potential attacks. The block's hash, a unique
      cryptographic fingerprint generated by processing its data through a hash
      function, changes if any alterations occur, serving as a tamper-proof
      seal. Moreover, each block includes the hash of the preceding block,
      creating a chain of blocks, thus solidifying its place in the sequence.
      Transaction data within the block represents its purpose, whether it's
      transferring cryptocurrencies or executing smart contracts. Additionally,
      there's a nonce—a random value miners must calculate to fit certain
      criteria in the proof of work algorithm. Successfully finding this nonce
      and verifying the block's integrity secures its addition to the
      blockchain, ensuring the entire ledger's security, consistency, and
      resistance to tampering.
      <br />
      <br />
      <b>Challenge:</b> Drag the different parts of the block to the right
      place.
      <br />
      <br />
      <b>Hint:</b> Click on the question marks to reveal an example of the
      property value.
    </p>

    <div class="mt-5">
      <CBlock></CBlock>
    </div>
    <div
      v-if="store.puzzles.block"
      class="flex items-center justify-center mt-4 mb-5"
    >
      <ButtonComponent
        text="Go to the next challenge"
        size="medium"
        color="white"
        :onClick="nextChallenge"
      />
    </div>
  </div>
</template>
